# Generated by Django 4.2.30 on 2026-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
